// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxNyAE-KGm1KvBfLTCSjP-eOVQSy1xjf4',
    appId: '1:522721501273:android:9819a44490745a5837d148',
    messagingSenderId: '522721501273',
    projectId: 'get-it-done-b9b4f',
    storageBucket: 'get-it-done-b9b4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC8LdxzEaGXMoqdsiP7o4Bl7BeAAWwcIY',
    appId: '1:522721501273:ios:dd6a2a193b696e7e37d148',
    messagingSenderId: '522721501273',
    projectId: 'get-it-done-b9b4f',
    storageBucket: 'get-it-done-b9b4f.appspot.com',
    iosClientId: '522721501273-obcnhed75viu1b24seha62eglag21avg.apps.googleusercontent.com',
    iosBundleId: 'com.example.com',
  );
}
